import Champion from './Champion.js';

//Patch 12.23.3
export default [
	new Champion('Aatrox', 'Aatrox', ['top']),
	new Champion('Ahri', 'Ahri', ['mid']),
	new Champion('Akali', 'Akali', ['top', 'mid']),
	new Champion('Akshan', 'Akshan', ['top', 'mid']),
	new Champion('Alistar', 'Alistar', ['support']),
	new Champion('Amumu', 'Amumu', ['jungle', 'support']),
	new Champion('Anivia', 'Anivia', ['mid']),
	new Champion('Annie', 'Annie', ['mid']),
	new Champion('Aphelios', 'Aphelios', ['adc']),
	new Champion('Ashe', 'Ashe', ['adc', 'support']),
	new Champion('AurelionSol', 'Aurelion Sol', ['mid']),
	new Champion('Azir', 'Azir', ['mid']),
	new Champion('Bard', 'Bard', ['support']),
	new Champion('Belveth', "Bel' Veth", ['jungle']),
	new Champion('Blitzcrank', 'Blitzcrank', ['support', 'jungle']),
	new Champion('Brand', 'Brand', ['mid', 'support']),
	new Champion('Braum', 'Braum', ['support']),
	new Champion('Caitlyn', 'Caitlyn', ['adc']),
	new Champion('Camille', 'Camille', ['top']),
	new Champion('Cassiopeia', 'Cassiopeia', ['top', 'mid']),
	new Champion('Chogath', "Cho'Gath", ['top', 'mid']),
	new Champion('Corki', 'Corki', ['mid']),
	new Champion('Darius', 'Darius', ['top']),
	new Champion('Diana', 'Diana', ['jungle', 'mid']),
	new Champion('Draven', 'Draven', ['adc']),
	new Champion('DrMundo', 'Dr. Mundo', ['top']),
	new Champion('Ekko', 'Ekko', ['jungle', 'mid']),
	new Champion('Elise', 'Elise', ['jungle']),
	new Champion('Evelynn', 'Evelynn', ['jungle']),
	new Champion('Ezreal', 'Ezreal', ['adc']),
	new Champion('Fiddlesticks', 'Fiddlesticks', ['jungle', 'support']),
	new Champion('Fiora', 'Fiora', ['top']),
	new Champion('Fizz', 'Fizz', ['mid']),
	new Champion('Galio', 'Galio', ['mid']),
	new Champion('Gangplank', 'Gangplank', ['top', 'mid']),
	new Champion('Garen', 'Garen', ['top']),
	new Champion('Gnar', 'Gnar', ['top']),
	new Champion('Gragas', 'Gragas', ['top', 'jungle', 'mid']),
	new Champion('Graves', 'Graves', ['top', 'jungle']),
	new Champion('Gwen', 'Gwen', ['top']),
	new Champion('Hecarim', 'Hecarim', ['jungle']),
	new Champion('Heimerdinger', 'Heimerdinger', ['top', 'mid', 'support']),
	new Champion('Illaoi', 'Illaoi', ['top']),
	new Champion('Irelia', 'Irelia', ['top', 'mid']),
	new Champion('Ivern', 'Ivern', ['jungle']),
	new Champion('Janna', 'Janna', ['support']),
	new Champion('JarvanIV', 'Jarvan IV', ['jungle']),
	new Champion('Jax', 'Jax', ['top']),
	new Champion('Jayce', 'Jayce', ['top', 'mid']),
	new Champion('Jhin', 'Jhin', ['adc']),
	new Champion('Jinx', 'Jinx', ['adc']),
	new Champion('Kaisa', "Kai'Sa", ['adc']),
	new Champion('Kalista', 'Kalista', ['adc']),
	new Champion('Karma', 'Karma', ['support', 'mid']),
	new Champion('Karthus', 'Karthus', ['jungle', 'adc']),
	new Champion('Kassadin', 'Kassadin', ['mid']),
	new Champion('Katarina', 'Katarina', ['mid']),
	new Champion('Kayle', 'Kayle', ['mid', 'top']),
	new Champion('Kayn', 'Kayn', ['jungle']),
	new Champion('Kennen', 'Kennen', ['top']),
	new Champion('Khazix', "Kha'Zix", ['jungle']),
	new Champion('Kindred', 'Kindred', ['jungle']),
	new Champion('Kled', 'Kled', ['top']),
	new Champion('KogMaw', "Kog'Maw", ['adc']),
	new Champion('KSante', "K'Sante", ['top']),
	new Champion('Leblanc', 'LeBlanc', ['mid']),
	new Champion('LeeSin', 'Lee Sin', ['jungle']),
	new Champion('Leona', 'Leona', ['support']),
	new Champion('Lillia', 'Lillia', ['jungle', 'top']),
	new Champion('Lissandra', 'Lissandra', ['mid']),
	new Champion('Lucian', 'Lucian', ['mid', 'bot']),
	new Champion('Lulu', 'Lulu', ['support']),
	new Champion('Lux', 'Lux', ['mid']),
	new Champion('Malphite', 'Malphite', ['top']),
	new Champion('Malzahar', 'Malzahar', ['mid']),
	new Champion('Maokai', 'Maokai', ['jungle', 'support', 'top']),
	new Champion('MasterYi', 'Master Yi', ['jungle']),
	new Champion('MissFortune', 'Miss Fortune', ['adc', 'support']),
	new Champion('Mordekaiser', 'Mordekaiser', ['top', 'jungle']),
	new Champion('Morgana', 'Morgana', ['support']),
	new Champion('Nami', 'Nami', ['support']),
	new Champion('Nasus', 'Nasus', ['top']),
	new Champion('Nautilus', 'Nautilus', ['support']),
	new Champion('Neeko', 'Neeko', ['mid']),
	new Champion('Nidalee', 'Nidalee', ['jungle']),
	new Champion('Nilah', 'Nilah', ['adc']),
	new Champion('Nocturne', 'Nocturne', ['jungle']),
	new Champion('Nunu', 'Nunu & Willump', ['jungle']),
	new Champion('Olaf', 'Olaf', ['top', 'jungle']),
	new Champion('Orianna', 'Orianna', ['mid']),
	new Champion('Ornn', 'Ornn', ['top']),
	new Champion('Pantheon', 'Pantheon', ['support', 'jungle', 'top', 'mid']),
	new Champion('Poppy', 'Poppy', ['jungle', 'top']),
	new Champion('Pyke', 'Pyke', ['support']),
	new Champion('Qiyana', 'Qiyana', ['jungle', 'mid']),
	new Champion('Quinn', 'Quinn', ['top']),
	new Champion('Rakan', 'Rakan', ['support']),
	new Champion('Rammus', 'Rammus', ['jungle']),
	new Champion('RekSai', "Rek'Sai", ['jungle']),
	new Champion('Rell', 'Rell', ['support']),
	new Champion('Renata', 'Renata Glasc', ['support']),
	new Champion('Renekton', 'Renekton', ['top', 'mid']),
	new Champion('Rengar', 'Rengar', ['jungle', 'top']),
	new Champion('Riven', 'Riven', ['top']),
	new Champion('Rumble', 'Rumble', ['top', 'mid']),
	new Champion('Ryze', 'Ryze', ['mid']),
	new Champion('Samira', 'Samira', ['adc']),
	new Champion('Sejuani', 'Sejuani', ['top', 'jungle']),
	new Champion('Senna', 'Senna', ['support']),
	new Champion('Seraphine', 'Seraphine', ['mid', 'adc', 'support']),
	new Champion('Sett', 'Sett', ['top', 'mid', 'support']),
	new Champion('Shaco', 'Shaco', ['jungle', 'support']),
	new Champion('Shen', 'Shen', ['top']),
	new Champion('Shyvana', 'Shyvana', ['top', 'jungle']),
	new Champion('Singed', 'Singed', ['top', 'mid']),
	new Champion('Sion', 'Sion', ['top']),
	new Champion('Sivir', 'Sivir', ['adc']),
	new Champion('Skarner', 'Skarner', ['jungle']),
	new Champion('Sona', 'Sona', ['support']),
	new Champion('Soraka', 'Soraka', ['support']),
	new Champion('Swain', 'Swain', ['top', 'mid', 'adc', 'support']),
	new Champion('Sylas', 'Sylas', ['top', 'mid']),
	new Champion('Syndra', 'Syndra', 'Syndra', ['mid']),
	new Champion('TahmKench', 'Tahm Kench', ['top', 'support']),
	new Champion('Taliyah', 'Taliyah', ['jungle', 'mid']),
	new Champion('Talon', 'Talon', ['jungle', 'mid']),
	new Champion('Taric', 'Taric', ['support']),
	new Champion('Teemo', 'Teemo', ['top']),
	new Champion('Thresh', 'Thresh', ['support']),
	new Champion('Tristana', 'Tristana', ['mid', 'adc']),
	new Champion('Trundle', 'Trundle', ['top', 'jungle']),
	new Champion('Tryndamere', 'Tryndamere', ['top']),
	new Champion('TwistedFate', 'Twisted Fate', ['mid']),
	new Champion('Twitch', 'Twitch', ['support', 'adc']),
	new Champion('Udyr', 'Udyr', ['top', 'jungle']),
	new Champion('Urgot', 'Urgot', ['top']),
	new Champion('Varus', 'Varus', ['mid', 'adc']),
	new Champion('Vayne', 'Vayne', ['top', 'adc']),
	new Champion('Veigar', 'Veigar', ['adc', 'mid']),
	new Champion('Velkoz', "Vel'koz", ['mid', 'support']),
	new Champion('Vex', 'Vex', ['mid']),
	new Champion('Vi', 'Vi', ['jungle']),
	new Champion('Viego', 'Viego', ['jungle']),
	new Champion('Viktor', 'Viktor', ['mid']),
	new Champion('Vladimir', 'Vladimir', ['top', 'mid']),
	new Champion('Volibear', 'Volibear', ['top', 'jungle']),
	new Champion('Warwick', 'Warwick', ['top', 'jungle']),
	new Champion('MonkeyKing', 'Wukong', ['top', 'jungle']),
	new Champion('Xayah', 'Xayah', ['adc']),
	new Champion('Xerath', 'Xerath', ['mid', 'support']),
	new Champion('XinZhao', 'Xin Zhao', ['jungle']),
	new Champion('Yasuo', 'Yasuo', ['top', 'mid', 'adc']),
	new Champion('Yone', 'Yone', ['top', 'mid']),
	new Champion('Yorick', 'Yorick', 'Yorick', ['top']),
	new Champion('Yuumi', 'Yuumi', ['support']),
	new Champion('Zac', 'Zac', ['top', 'jungle']),
	new Champion('Zed', 'Zed', ['jungle', 'mid']),
	new Champion('Zeri', 'Zeri', ['adc']),
	new Champion('Ziggs', 'Ziggs', ['mid', 'adc']),
	new Champion('Zilean', 'Zilean', ['mid', 'support']),
	new Champion('Zoe', 'Zoe', ['mid']),
	new Champion('Zyra', 'Zyra', ['support']),
];
